---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/JonasHess/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/repos/dotfiles
dotfiles_repo_version: main
dotfiles_files:
  - .gitignore
  - .inputrc
  - .nvimrc
  - .oh-my-zsh
  - .osx
  - .p10k.zsh
  - .tmux.conf
  - .tmux.conf.local
  - .config
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - argocd
  - argocd-autopilot
  - autoconf
  - awscli
  - azure-cli
  - bash-completion
  - bat
  - curl
  - highlight
  - doxygen
  - fzf
  - ffmpeg
  - gettext
  - unar
  - gh
  - gifsicle
  - git
  - atool
  - go
  - gpg
  - helm
  - htop
  - sevenzip
  - httpie
  - iperf
  - istioctl
  - jenv
  - jq
  - pipx
  - k9s
  - kubernetes-cli
  - lazydocker
  - lazygit
  - less
  - lf
  - libevent
  - neofetch
  - neovim
  - nmap
  - node
  - nvm
  - openssl
  - php
  - ranger
  - rust
  - speedtest-cli
  - sqlite
  - ssh-copy-id
  - tldr
  - tmux
  - toilet
  - tree-sitter
  - wget
  - wireshark
  - yarn
  - yq
  - zellij
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - firefox
  # - alacritty
  # - google-chrome
  # - chromedriver
  # - amazon-photos
  - brave-browser
  - chromium
  - rectangle
  - dbeaver-community
  - docker
  - drawio
  - font-jetbrains-mono-nerd-font
  - google-cloud-sdk
  - handbrake
  - intellij-idea
  - licecap
  - logi-options-plus
  - microsoft-office
  - microsoft-teams
  - pycharm
  - sequel-ace
  - kdiff3
  - slack
  - spotify
  - sublime-text
  - transmit
  - visual-studio-code
  - vlc
  - elgato-camera-hub

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
  # - ranger-fm
  # - img2txt

# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
